Try inline action
Signed-off-by: Ryan Nett <JNett96@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,8 +41,11 @@ jobs:
       - name: Run lint checks
         run: |
           mvn compiler:compile -Pdev,jdk11 -B -U -e
-      - name: Check for un-committed generation
-        uses: ./.github/actions/check-generation
+      - shell: bash
+        run: |
+          git add .
+          git update-index --refresh
+          git diff-index --name-status --exit-code HEAD tensorflow-core/tensorflow-core-api/src/gen/** > changes.txt || echo "::error file=changes.txt,line=0,title=\"Un-commited generation\"::Generated classes after build do not match what was committed"
   check-format:
     if: github.event_name == 'pull_request'
     runs-on: ubuntu-latest
